### ISSUE TITLE
Intermittent Error on State Refresh

### ISSUE THREAD

**Issue by jxg81** [jxg81/homebridge-actron-que#3]
Occasional error resulting in failure of Actron plugin

TypeError: Cannot read properties of undefined (reading 'EnabledZones')
    at QueApi.getStatus (/var/lib/homebridge/node_modules/.pnpm/homebridge-actron-que@1.2.2/node_modules/homebridge-actron-que/src/queApi.ts:325:86)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HvacUnit.getStatus (/var/lib/homebridge/node_modules/.pnpm/homebridge-actron-que@1.2.2/node_modules/homebridge-actron-que/src/hvac.ts:53:20)
    at MasterControllerAccessory.hardUpdateDeviceCharacteristics (/var/lib/homebridge/node_modules/.pnpm/homebridge-actron-que@1.2.2/node_modules/homebridge-actron-que/src/masterControllerAccessory.ts:87:27)

**Comment by jxg81** [comment]
Testing beta release to confirm issue has been managed 
[1.2.3-beta.2](https://www.npmjs.com/package/homebridge-actron-que/v/1.2.3-beta.2)
